[tools]
go = "1.25.5"

[tasks.fmt]
run = "rg --files -g '*.go' | xargs gofmt -w"

[tasks.tidy]
run = "go mod tidy"

[tasks.test]
run = "go test ./..."

[tasks.check]
depends = ["fmt", "tidy", "test"]
